name: Deployment

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v2
      - name: Install licensed
        run: |
          pm2 deploy production update
      - name: Print
        run: echo ${{secretes.PORTFOLIO_SERVER_SSH_PRIVATE_KEY}}
