name: Deployment

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PROFILE" > ~/.ssh/config
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/portfolio.key
          echo "$GITKEY" > ~/.ssh/GitKey
          sudo chmod 600 ~/.ssh/GitKey
          sudo chmod 600 ~/.ssh/portfolio.key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/GitKey
          ssh -T git@github.com
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PORTFOLIO_SERVER_SSH_PRIVATE_KEY}}
          GITKEY: ${{secrets.GIT_KEY}}
          SSH_PROFILE: ${{secrets.SSH_PROFILE}}
