name: Deployment

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v2
      - name: Install licensed
        run: |
          echo "sss"
