name: Deployment

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          cat ./deploy.key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PORTFOLIO_SERVER_SSH_PRIVATE_KEY}}
