name: Deployment

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PROFILE" > ~/.ssh/config
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/portfolio.key
          echo "$GITKEY" > ~/.ssh/GitKey
          sudo chmod 600 ~/.ssh/GitKey
          sudo chmod 600 ~/.ssh/portfolio.key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/GitKey
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PORTFOLIO_SERVER_SSH_PRIVATE_KEY}}
          GITKEY: ${{secrets.GIT_KEY}}
          SSH_PROFILE: ${{secrets.SSH_PROFILE}}
          KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}

      - name: Install PM2
        run: sudo npm i -g pm2 &>/dev/null
        shell: bash

      - name: Running Deployment Script
        run: |
          git clone git@github.com:algo7/aviv_portifolio_arlo.git
          cd aviv_portifolio_arlo
          echo "$ECOF" > ./ecosystem.json
          pm2 deploy ecosystem.json production update
        shell: bash
        env:
          ECOF: ${{secrets.ECOSYSTEM_FILE}}
