name: Deployment

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PROFILE" > ~/.ssh/config
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/portfolio.key
          git clone git clone aviv_portifolio_arlo
          cd git clone aviv_portifolio_arlo
          echo "$ECOF" > ./ecosystem.json
          cat ./ecosystem.json
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PORTFOLIO_SERVER_SSH_PRIVATE_KEY}}
          ECOF: ${{secrets.ECOSYSTEM_FILE}}
          SSHCONF: ${{secrets.SSH_PROFILE}}
